### ISSUE TITLE
XAML markup support

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-app-rs#13]
First of all, thank you for patiently responding to all my questions 😅

I'm wondering, do you have any plans to support building WinUI 3 apps using XAML markup (so not in code-behind)?

I'd assume that would require a XAML compiler to kick off, but then ~it should be possible to load it using the [XamlReader class](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.markup.xamlreader?view=winui-3.0)~ ...then what?.. 😅

Do you have any plans or thoughts on how that might be supported? 🤔

**Comment by kennykerr** [comment]
Thanks, its our desire to support markup. Otherwise, Xaml is pretty lame. 😉 

The Xaml compiler is only needed for binding expressions, but I'm hopeful we can do that natively in Rust and not require a separate Xaml compiler for Rust. I've already demonstrated this is possible in C++. 

The `windows-app` crate is the start of more specific WinUI support. I'm not sure when we'll get it all done though. It's quite a lot of work. 😊

**Comment by handicraftsman** [comment]
A DSL might be used, similar to https://crates.io/crates/vgtk
